accounts/urls.py
from django.urls import path

from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

blog/urls.py
from django.urls import path, include
from .views import (
    BlogListView,
    BlogDetailView,
    BlogCreateView,
    BlogCreateContent,
    BlogUpdateView,
    BlogDeleteView,
    BlogContact,
    BlogAbout,
    BlogPolicy,
    BlogTeam,
)

# The empty string tells Python to match all values
# The urls are custom made, just be professional.
urlpatterns = [
    path('post/<int:pk>/delete', BlogDeleteView.as_view(), name='post_delete'),
    path('post/<int:pk>/edit', BlogUpdateView.as_view(), name='post_edit'),
    path('post/new/', BlogCreateView.as_view(), name='post_new'),
    path('post/new/<int:pk>/content/', BlogCreateContent.as_view(), name='post_content'),
    path('post/<int:pk>/', BlogDetailView.as_view(), name='post_detail'),
    path('contact', BlogContact.as_view(), name='contact'),
    path('chat', BlogAbout.as_view(), name='chat'),
    path('policy', BlogPolicy.as_view(), name='policy'),
    path('about', BlogTeam.as_view(), name='about'),
    path('', BlogListView.as_view(), name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.models import Post
from blog.sitemaps import (
    StaticViewSitemap,
    StaticViewContact,
    StaticViewAbout,
    StaticViewPolicy,
    StaticViewTeam,
)
from django.contrib.sitemaps import GenericSitemap # new
from django.contrib.sitemaps.views import sitemap # new
# The empty string means URL requests should be redirected to the blog's URLs for further instruction.


sitemaps = {
    'blog': GenericSitemap({
        'queryset': Post.objects.all()
    }, priority=0.9),
    'static': StaticViewSitemap,
    'contacts': StaticViewContact,
    'about': StaticViewAbout,
    'policy': StaticViewPolicy,
    'team': StaticViewTeam,
}

urlpatterns = [
    path('thebossreecac/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('blog.urls')),
    path('sitemap.xml', sitemap, # new
         {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
# Create your models here.
# Do research on the Django field types


class Post(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        # User,
        'auth.User',
        on_delete=models.CASCADE,
    )

    img = models.CharField(max_length=60)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])


class Content(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    head = models.CharField(max_length=200)
    body = models.TextField()

    def __str__(self):
        return self.head

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

# Create your views here.


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.url'

blog/views.py
from django.shortcuts import render, HttpResponse
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Post, Content
from django.urls import reverse_lazy

# Create your views here.
# You can use the context_object_name to explicitly name your context object.


class BlogTeam(TemplateView):
    template_name = 'navbar/team.html'


class BlogPolicy(TemplateView):
    template_name = 'navbar/policy.html'


class BlogContact(TemplateView):
    template_name = 'navbar/contact.html'


class BlogAbout(TemplateView):
    template_name = 'navbar/about_me.html'


class BlogListView(ListView):
    model = Post
    template_name = 'home.html'


class BlogDetailView(DetailView):
    model = Post
    template_name = 'post_detail.html'


# Part of the Forms chapter in the book.
class BlogCreateView(CreateView):
    model = Post
    template_name = 'post_new.html'
    # Specify the fields the user needs to input.
    fields = ['title', 'author', 'img']


class BlogCreateContent(CreateView):
    model = Content
    template_name = 'post_content.html'
    # Specify the fields the user needs to input.
    fields = ['head', 'body']


class BlogUpdateView(UpdateView):
    model = Post
    template_name = 'post_edit.html'
    fields = ['title', 'img']


class BlogDeleteView(DeleteView):
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('home')

accounts/templates/signup.html
{% extends 'base.html' %}

{% block content %}
<h2>Sign up</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
</form>
{% endblock content %}

blog/templates/base.html
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Reecac{% endblock %}</title>
    <meta name="description" content="Have you ever been stuck thinking about
    what to do before graduating high school or college? Well, this blog is a way to either guide or improve you.">
    <meta name="keywords" content="career planning before high school, advice in high school, life before college, reecac">
    <meta name="author" content="Teagan Ramos-Ewing">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link href="{% static 'css/effects.css' %}" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <script data-ad-client="ca-pub-6880112665291219" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script type="text/javascript" src="{% static 'jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/fireflies.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/fireflies.css' %}">
</head>
<body>
<canvas id="canvas">
</canvas>
<div id="myHeader">
    <header>
        <h1 class="green-neon">Reecac</h1>

        <div class="main">
            <div class="nav">
                <ol>
                    <li><a href="{% url 'home' %}">Home</a></li>
                    <li><a href="{% url 'chat' %}">Public Chat</a></li>
                    <li><a href="{% url 'policy' %}">Privacy Policy</a></li>
                    <li><a href="{% url 'contact' %}">Contact Us</a></li>
                    <li><a href="{% url 'about' %}">About Us</a></li>
                    <li class="animation"></li>
                </ol>
            </div>
        </div>
    </header>

</div>
<div class="scroll" id="style-1">


    {% if user.is_authenticated %}
    <p><a href="{% url 'logout' %}">Log Out</a></p>
    <a href="{% url 'post_new' %}">+ New Blog Post</a>
    {% endif %}
    <div>
    {% block content %}
    {% endblock content %}
    </div>

</div>
<script>
window.onscroll = function() {myFunction()};

var header = document.getElementById("myHeader");
var sticky = header.offsetTop;

function myFunction() {
  if (window.pageYOffset > sticky) {
    header.classList.add("sticky");
  } else {
    header.classList.remove("sticky");
  }
}
</script>
</body>
</html>

blog/templates/fly.html
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Reecac{% endblock %}</title>
    <meta name="description" content="Have you ever been stuck thinking about
    what to do before graduating high school or college? Well, this blog is a way to either guide or improve you.">
    <meta name="keywords" content="career, advice, life">
    <meta name="author" content="Teagan Ramos-Ewing">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
    <link href="{% static 'css/effects.css' %}" rel="stylesheet">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <script data-ad-client="ca-pub-6880112665291219" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script type="text/javascript" src="{% static 'jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/fireflies.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/fireflies.css' %}">
<body>
<canvas id="canvas">
</canvas>
<div class="no-scroll">
    <header>
        <h1 class="green-neon">Reecac</h1>
        <div class="main">
            <div class="nav">
                <ol>
                    <li><a href="{% url 'home' %}">Home</a></li>
                    <li><a href="{% url 'chat' %}">Public Chat</a></li>
                    <li><a href="{% url 'policy' %}">Privacy Policy</a></li>
                    <li><a href="{% url 'contact' %}">Contact Us</a></li>
                    <li><a href="{% url 'about' %}">About Us</a></li>
                    <li class="animation"></li>
                </ol>
            </div>
        </div>
    </header>


    {% if user.is_authenticated %}
    <p><a href="{% url 'logout' %}">Log Out</a></p>
    {% endif %}
    <div>
        {% block content %}
        {% endblock content %}
    </div>
</div>
</body>
</html>

blog/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1 class="blue-neon" style="padding-left:20%;width:40%;padding-right:40%;">
    NEWEST POST
</h1>
{% for post in object_list reversed %}
{% if forloop.first %}
<div class="column-img">
    <div class="container">
    {% with 'img/'|add:post.img|add:'.PNG' as image_static %}
    <img src="{% static image_static %}" style="max-height:50%,max-width:50%;"/>
    {% endwith %}
        </div>
</div>
<div class="column-text">
    <h2 class="blue-neon" style="padding-left:20%;width:60%;padding-right:20%;">{{ post.title }}</h2>
    {% for content in post.content_set.all %}
    <h2 style="color: white;text-align: left;">{{ content.head }}</h2>
    <p style="color:white;text-align: left;padding-left:2%;"> {{ content.body }}</p>
    {% endfor %}
</div>
{% endif %}
{% endfor %}
<div class="column-post">
<h1 class="blue-neon" style="padding-left:20%;width:40%;padding-right:40%;padding-top:2%;">
    OLD POSTS
</h1>
<!--object_list comes from the ListView in the BlogListView class-->

 {% for post in object_list reversed %}
    {% if forloop.first %}
<!--get all the objects, it has the attributes of the post model-->
    {% else %}
  <div class="post-entry" style="padding-left: 20%;width: 40%;padding-right: 40%;">
      <h2 class="blog-left"><a href="{% url 'post_detail' post.pk %}">{{ post.title }}</a></h2>
  </div>
    {% endif %}
 {% endfor %}

</div>
{% endblock content %}
<!--To add static files for in production you need a Content Delivery Network (CDN)-->

blog/templates/navbar/about_me.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Reecac - Chat{% endblock %}
{% block content %}
<link href="{% static 'css/about.css' %}" rel="stylesheet">
<div class="about-mid">
    {% include 'public.html' %}
</div>
{% endblock content %}

blog/templates/navbar/contact.html
{% extends 'fly.html' %}
{% block title %}Reecac - Contact Us{% endblock %}
{% load static %}
{% block content %}
<script src="https://kit.fontawesome.com/e25b852c87.js" crossorigin="anonymous"></script>
<link href="{% static 'css/navbar.css' %}" rel="stylesheet">
<h1 class="contacts">Contacts</h1>
<h3 class="email">Email: gradeerG7@gmail.com</h3>
<h1 class="follow"> Follow me</h1>
<div class="container">
    <a href="https://www.facebook.com/Reecac-588190138485734" id="face"><i class="fab fa-facebook"></i></a>
    <a href="https://www.instagram.com/reecacofficial//" id="insta"><i class="fab fa-instagram"></i></a>
</div>

{% endblock content %}

blog/templates/navbar/team.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Reecac - About Us{% endblock %}
{% block content %}
<link href="{% static 'css/team.css' %}" rel="stylesheet">
<div class="about-mid">
    <h2 class="purple-neon">Developers</h2>
    <ul>
        <li><span style="font-size: 140%;">Teagan Ramos</span><br>Teagan Ramos is a dude who likes to code. He's a 2020 graduate, but that didn't stop him from doing what
        he loves. He wanted to continue programming, so he researched and eventually obtained the skills to make this website. But it
        wasn't done alone, he had many friends to assist and help him with the process. Apart from the website, he also made this app called QuickSchedule with his
        first-in command, Dylan Tuten. This was the beginning of a great friendship and many programming projects to come. He's also in the credits of this game called <a href="https://dylandummy.itch.io/cominghome">Coming Home</a>.</li>
        <br>
        <li><span style="font-size: 140%;">Dylan Tuten</span><br>Dylan Tuten is a big boy who does computer things.
            He won the Congressional App Challenge in 2019 with his best friend in the whole wide world, Teagan for his work on <a href="https://www.congressionalappchallenge.us/19-fl10/">QuickSchedule</a> freshman year.
            He made a game called <a href="https://dylandummy.itch.io/cominghome">Coming Home</a> in freshman year of high school. He later made a game for the Adult Swim show <a href="https://www.adultswim.com/videos/electronic-game-information">Electronic Game Information</a>, <a href="https://twitter.com/egiwithrobby/status/1288174751576293377">"Alan's Game"</a>, summer after freshman year.
            Dylan Tuten is now working on a game called Cabin Fever, and will post updates on his <a href="https://twitter.com/dylandummy">twitter</a>. He's almost a sophmore in highschool.</li>
    </ul>
    <h2 class="purple-neon">Contributors</h2>
    <ul>
        <li>Justin Alvarez</li>
        <li>Alex Robel</li>
        <li>Dinh Pham</li>
    </ul>
    <h2 class="purple-neon">About The Website</h2>
    <p style="padding-inline-start: 20px;">
        We aim to provide our experience and thoughts on how to turn a passion into a career, and provide a place for experienced and inexperienced coders alike to share their goals and project ideas with the community.
        And by viewing this blog I hope you will advance earlier than we did.
    </p>
    <p style="padding-inline-start: 20px;">
        REECAC is an acronym. It stands for Read, Entertain & Exhibit Coding Achievements with your Community.
    </p>
</div>
{% endblock content %}

blog/templates/post_content.html
{% extends 'base.html' %}
{% block content %}
<h1>New post</h1>
<!--We use the POST method for sending data, we use the GET method to receive data (search bar)-->
<!--USE THE CSRF_TOKEN TAG FOR ALL FORMS-->
<form action="" method="post">{% csrf_token %}
    <!--Outputs the form data as a paragraph element-->
    {{ form.as_p }}
    <!--The value is the name of the input-->
    <input type="submit" value="Save" />
</form>
{% endblock content %}

blog/templates/post_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Content</h1>
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ post.title }}"?</p>
    <input type="submit" value="Confirm" />
</form>
{% endblock content %}

blog/templates/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="column-img" style="margin-top: 3%;">
    {% with 'img/'|add:post.img|add:'.PNG' as image_static %}
    <img src="{% static image_static %}" style="width:100%;"/>
    {% endwith %}
</div>
<div class="column-text">
    <h2 style="color:white">{{ post.title }}</h2>
    <p class="body-text">{{ post.body }}</p>
    {% for content in post.content_set.all %}
        <h2 style="color: white;text-align: left;">{{ content.head }}</h2>
        <p style="color:white;text-align: left;"> {{ content.body }}</p>
    {% endfor %}
</div>
{% if user.is_authenticated %}
<p><a href="{% url 'post_edit' post.id %}">+ Edit Blog Post</a></p>
<p><a href="{% url 'post_delete' post.pk %}">+ Delete Blog Post</a></p>
{% endif %}
{% endblock content %}

blog/templates/post_edit.html
{% extends 'base.html' %}

{% block content %}
<h1>Edit post</h1>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>
{% endblock content %}

blog/templates/post_new.html
{% extends 'base.html' %}
{% block content %}
    <h1>New post</h1>
<!--We use the POST method for sending data, we use the GET method to receive data (search bar)-->
<!--USE THE CSRF_TOKEN TAG FOR ALL FORMS-->
    <form action="" method="post">{% csrf_token %}
        <!--Outputs the form data as a paragraph element-->
        {{ form.as_p }}
        <!--The value is the name of the input-->
        <input type="submit" value="Save" />
    </form>
{% endblock content %}

blog/templates/public.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
  <script type='text/javascript' src='https://cdn.scaledrone.com/scaledrone.min.js'></script>
  <!--<script type='text/javascript' src='http://0.0.0.0:8080/scaledrone.js'></script>-->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <script src="{% static 'js/width.js' %}"></script>
  <style>
  :root {
    --height-var: 600px;
    --width-var: 600px;
  }
  @media screen and (orientation: landscape) and (max-width: 3000px) and (max-height: 1500px){
    html, body {
      box-sizing: border-box;
      font-family: Candara;
	  background-color: #414141;
    }
    }
    @media screen and (orientation: landscape) and (max-width: 1400px) and (max-height: 1100px){
      html, body {
      height: var(--height-var);
      width: var(--width-var);
      display: inline-table;
      box-sizing: border-box;
      font-family: Candara;
	  background-color: #414141;
    }
      }
     @media screen and (orientation: landscape) and (max-width: 1400px) and (max-height: 800px){
      html, body {
      height: var(--height-var);
      width: var(--width-var);
      display: inline-table;
      box-sizing: border-box;
      font-family: Candara;
	  background-color: #414141;
    }
     }
     @media screen and (max-width: 1100px) and (max-height: 2200px){
     html, body {
      height: var(--height-var);
      width: var(--width-var);
      display: inline-table;
      box-sizing: border-box;
      font-family: Candara;
	  background-color: #414141;
    }
     }

	.chat {
		margin-left: auto;
		margin-right: auto;
		width: 65%
	}
    .members-count,
    .members-list,
    .messages {
      border: 2px solid #e4e4e4;
	  border-radius: 6px;
      padding: 15px;
      font-family: Candara;
      margin-bottom: 15px;
    }

    .messages {
      flex-shrink: 1;
      font-family: Candara;
      overflow: auto;
    }

    .message {
      padding: 5px 0;
	  color: white;
      font-family: Candara;
    }
    .message .member {
      display: inline-block;
      font-family: Candara;
    }

    .member {
      padding-right: 10px;
      font-family: Candara;
      position: relative;
    }

    .message-form {
      display: flex;
      font-family: Candara;
      border: 2px solid #e4e4e4;
	  border-radius: 6px;
      flex-shrink: 0;
    }
    .message-form__input {
      flex-grow: 1;
      font-family: Candara;
      border: 1px solid #dfdfdf;
      padding: 10px 15px;
      font-size: 16px;
	  background-color: #414141;
	  color: white;
    }
  </style>
</head>
<body>
<div class="chat">
  <div class="members-list">-</div>
  <div class="messages"></div>
  <form class="message-form" onsubmit="return false;">
    {% csrf_token %}
    <input class="message-form__input" placeholder="Type your message and press enter." type="text"/>
  </form>
</div>
  <script src="{% static 'js/public.js' %}"></script>
</body>

</html>